export const homeObjOne = {
    lightBg:false,
    primary:true,
    imgStart:'',
    lightTextDesc:true,
    buttonLabel:'Get Started',
    description:'We help your business to grow up & find new ways, new opportunities...',
    headline:'Collaborations makes your business better',
    lightText:true,
    img:require('../../images/undraw_online_collaboration_7pfp.svg'),
    alt:'Image',
start: '',
}
export const homeObjTwo = {
    lightBg:true,
    primary:false,
    imgStart:'start',
    lightTextDesc:false,
    buttonLabel:'Watch it',
    description:'It helps to organized your working day or anything else...',
    headline:'ToDo list',
    lightText:false,
    img:require('../../images/undraw_real_time_collaboration_c62i.svg'),
    alt:'Image',
    start: 'true',
}