export const homeObjOne = {
    lightBg:false,
    primary:true,
    imgStart:'',
    lightTextDesc:true,
    buttonLabel:'Get Started',
    description:'We help your business grow, find new ways and opportunities.Your company will become the best in the market and ...',
    headline:'Cooperation with us is exactly what you need.',
    lightText:true,
    img:require('../../images/undraw_online_collaboration_7pfp.svg'),
    alt:'Image',
start: '',
}
export const homeObjTwo = {
    lightBg:  true,
    primary: false,
    imgStart:'start',
    lightTextDesc: false,
    buttonLabel:'Watch it',
    description:'Just think positive and be nice...',
    headline:'Work.Find.Chat',
    lightText: false,
    img:require('../../images/undraw_real_time_collaboration_c62i.svg'),
    alt:'Image',
    start: 'true',
}
